spring:
  application:
    name: ms-improvements
  # H2 database configurations
  datasource:
    url: jdbc:h2:file:./ms-improvements/improvements_data
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mq:
  queues:
    monitoring-improvements-status: monitoring-improvements-status
